### ISSUE TITLE
Regen the data

### ISSUE THREAD

**Issue by bambooforest** [cldf-datasets/bdproto#3]
After adding the homeland data and fixing a bunch of inconsistencies in bibtex IDs, the bdproto data need to be regenerated at CLDF.

Note the changes in the field names:

* HomelandLatitude
* HomelandLongitude
* HomelandComments

And:

https://github.com/cldf-datasets/bdproto/issues/2

Let's wait on this until this issue is closed:

https://github.com/bdproto/bdproto/issues/66

**Comment by bambooforest** [comment]
Make sure to notify Tarik when we close.

**Comment by J22Melody** [comment]
Okay noted, I will do this once https://github.com/bdproto/bdproto/issues/66 is closed.

**Comment by bambooforest** [comment]
Closed by #6
